<?php
/**
 * AnulacionRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * AnulacionRequest Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AnulacionRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AnulacionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cantida_de_ncf_anulados' => '\Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress',
        'detalle_anulacion' => '\Ecfx\EcfDgii\Model\DetalleAnulacionRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cantida_de_ncf_anulados' => null,
        'detalle_anulacion' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cantida_de_ncf_anulados' => false,
        'detalle_anulacion' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cantida_de_ncf_anulados' => 'cantidaDeNcfAnulados',
        'detalle_anulacion' => 'detalleAnulacion'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cantida_de_ncf_anulados' => 'setCantidaDeNcfAnulados',
        'detalle_anulacion' => 'setDetalleAnulacion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cantida_de_ncf_anulados' => 'getCantidaDeNcfAnulados',
        'detalle_anulacion' => 'getDetalleAnulacion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cantida_de_ncf_anulados', $data ?? [], null);
        $this->setIfExists('detalle_anulacion', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cantida_de_ncf_anulados'] === null) {
            $invalidProperties[] = "'cantida_de_ncf_anulados' can't be null";
        }
        if ($this->container['detalle_anulacion'] === null) {
            $invalidProperties[] = "'detalle_anulacion' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cantida_de_ncf_anulados
     *
     * @return \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress
     */
    public function getCantidaDeNcfAnulados()
    {
        return $this->container['cantida_de_ncf_anulados'];
    }

    /**
     * Sets cantida_de_ncf_anulados
     *
     * @param \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress $cantida_de_ncf_anulados cantida_de_ncf_anulados
     *
     * @return self
     */
    public function setCantidaDeNcfAnulados($cantida_de_ncf_anulados)
    {
        if (is_null($cantida_de_ncf_anulados)) {
            throw new \InvalidArgumentException('non-nullable cantida_de_ncf_anulados cannot be null');
        }
        $this->container['cantida_de_ncf_anulados'] = $cantida_de_ncf_anulados;

        return $this;
    }

    /**
     * Gets detalle_anulacion
     *
     * @return \Ecfx\EcfDgii\Model\DetalleAnulacionRequest[]
     */
    public function getDetalleAnulacion()
    {
        return $this->container['detalle_anulacion'];
    }

    /**
     * Sets detalle_anulacion
     *
     * @param \Ecfx\EcfDgii\Model\DetalleAnulacionRequest[] $detalle_anulacion detalle_anulacion
     *
     * @return self
     */
    public function setDetalleAnulacion($detalle_anulacion)
    {
        if (is_null($detalle_anulacion)) {
            throw new \InvalidArgumentException('non-nullable detalle_anulacion cannot be null');
        }
        $this->container['detalle_anulacion'] = $detalle_anulacion;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


