<?php
/**
 * AnulacionListResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * AnulacionListResponse Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AnulacionListResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AnulacionListResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'anulacion_id' => 'string',
        'tenant_id' => 'string',
        'company_rnc' => 'string',
        'cantidade_ncf_anulados' => '\Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress',
        'detalle_anulacion' => '\Ecfx\EcfDgii\Model\DetalleAnulacionRequestDto[]',
        'response' => '\Ecfx\EcfDgii\Model\RespuestaAnulacionRango',
        'status_code' => '\Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress',
        'file_name' => 'string',
        'fecha_hora_anulacione_ncf' => '\DateTime',
        'created_on' => '\DateTime',
        'updated_on' => '\DateTime',
        'created_by' => 'string',
        'updated_by' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'anulacion_id' => 'uuid',
        'tenant_id' => 'uuid',
        'company_rnc' => null,
        'cantidade_ncf_anulados' => null,
        'detalle_anulacion' => null,
        'response' => null,
        'status_code' => null,
        'file_name' => null,
        'fecha_hora_anulacione_ncf' => 'date-time',
        'created_on' => 'date-time',
        'updated_on' => 'date-time',
        'created_by' => null,
        'updated_by' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'anulacion_id' => false,
        'tenant_id' => false,
        'company_rnc' => false,
        'cantidade_ncf_anulados' => false,
        'detalle_anulacion' => true,
        'response' => true,
        'status_code' => false,
        'file_name' => false,
        'fecha_hora_anulacione_ncf' => false,
        'created_on' => false,
        'updated_on' => false,
        'created_by' => false,
        'updated_by' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'anulacion_id' => 'anulacionId',
        'tenant_id' => 'tenantId',
        'company_rnc' => 'companyRnc',
        'cantidade_ncf_anulados' => 'cantidadeNCFAnulados',
        'detalle_anulacion' => 'detalleAnulacion',
        'response' => 'response',
        'status_code' => 'statusCode',
        'file_name' => 'fileName',
        'fecha_hora_anulacione_ncf' => 'fechaHoraAnulacioneNCF',
        'created_on' => 'createdOn',
        'updated_on' => 'updatedOn',
        'created_by' => 'createdBy',
        'updated_by' => 'updatedBy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'anulacion_id' => 'setAnulacionId',
        'tenant_id' => 'setTenantId',
        'company_rnc' => 'setCompanyRnc',
        'cantidade_ncf_anulados' => 'setCantidadeNcfAnulados',
        'detalle_anulacion' => 'setDetalleAnulacion',
        'response' => 'setResponse',
        'status_code' => 'setStatusCode',
        'file_name' => 'setFileName',
        'fecha_hora_anulacione_ncf' => 'setFechaHoraAnulacioneNcf',
        'created_on' => 'setCreatedOn',
        'updated_on' => 'setUpdatedOn',
        'created_by' => 'setCreatedBy',
        'updated_by' => 'setUpdatedBy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'anulacion_id' => 'getAnulacionId',
        'tenant_id' => 'getTenantId',
        'company_rnc' => 'getCompanyRnc',
        'cantidade_ncf_anulados' => 'getCantidadeNcfAnulados',
        'detalle_anulacion' => 'getDetalleAnulacion',
        'response' => 'getResponse',
        'status_code' => 'getStatusCode',
        'file_name' => 'getFileName',
        'fecha_hora_anulacione_ncf' => 'getFechaHoraAnulacioneNcf',
        'created_on' => 'getCreatedOn',
        'updated_on' => 'getUpdatedOn',
        'created_by' => 'getCreatedBy',
        'updated_by' => 'getUpdatedBy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('anulacion_id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('company_rnc', $data ?? [], null);
        $this->setIfExists('cantidade_ncf_anulados', $data ?? [], null);
        $this->setIfExists('detalle_anulacion', $data ?? [], null);
        $this->setIfExists('response', $data ?? [], null);
        $this->setIfExists('status_code', $data ?? [], null);
        $this->setIfExists('file_name', $data ?? [], null);
        $this->setIfExists('fecha_hora_anulacione_ncf', $data ?? [], null);
        $this->setIfExists('created_on', $data ?? [], null);
        $this->setIfExists('updated_on', $data ?? [], null);
        $this->setIfExists('created_by', $data ?? [], null);
        $this->setIfExists('updated_by', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets anulacion_id
     *
     * @return string|null
     */
    public function getAnulacionId()
    {
        return $this->container['anulacion_id'];
    }

    /**
     * Sets anulacion_id
     *
     * @param string|null $anulacion_id anulacion_id
     *
     * @return self
     */
    public function setAnulacionId($anulacion_id)
    {
        if (is_null($anulacion_id)) {
            throw new \InvalidArgumentException('non-nullable anulacion_id cannot be null');
        }
        $this->container['anulacion_id'] = $anulacion_id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string|null $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets company_rnc
     *
     * @return string|null
     */
    public function getCompanyRnc()
    {
        return $this->container['company_rnc'];
    }

    /**
     * Sets company_rnc
     *
     * @param string|null $company_rnc company_rnc
     *
     * @return self
     */
    public function setCompanyRnc($company_rnc)
    {
        if (is_null($company_rnc)) {
            throw new \InvalidArgumentException('non-nullable company_rnc cannot be null');
        }
        $this->container['company_rnc'] = $company_rnc;

        return $this;
    }

    /**
     * Gets cantidade_ncf_anulados
     *
     * @return \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress|null
     */
    public function getCantidadeNcfAnulados()
    {
        return $this->container['cantidade_ncf_anulados'];
    }

    /**
     * Sets cantidade_ncf_anulados
     *
     * @param \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress|null $cantidade_ncf_anulados cantidade_ncf_anulados
     *
     * @return self
     */
    public function setCantidadeNcfAnulados($cantidade_ncf_anulados)
    {
        if (is_null($cantidade_ncf_anulados)) {
            throw new \InvalidArgumentException('non-nullable cantidade_ncf_anulados cannot be null');
        }
        $this->container['cantidade_ncf_anulados'] = $cantidade_ncf_anulados;

        return $this;
    }

    /**
     * Gets detalle_anulacion
     *
     * @return \Ecfx\EcfDgii\Model\DetalleAnulacionRequestDto[]|null
     */
    public function getDetalleAnulacion()
    {
        return $this->container['detalle_anulacion'];
    }

    /**
     * Sets detalle_anulacion
     *
     * @param \Ecfx\EcfDgii\Model\DetalleAnulacionRequestDto[]|null $detalle_anulacion detalle_anulacion
     *
     * @return self
     */
    public function setDetalleAnulacion($detalle_anulacion)
    {
        if (is_null($detalle_anulacion)) {
            array_push($this->openAPINullablesSetToNull, 'detalle_anulacion');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('detalle_anulacion', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['detalle_anulacion'] = $detalle_anulacion;

        return $this;
    }

    /**
     * Gets response
     *
     * @return \Ecfx\EcfDgii\Model\RespuestaAnulacionRango|null
     */
    public function getResponse()
    {
        return $this->container['response'];
    }

    /**
     * Sets response
     *
     * @param \Ecfx\EcfDgii\Model\RespuestaAnulacionRango|null $response response
     *
     * @return self
     */
    public function setResponse($response)
    {
        if (is_null($response)) {
            array_push($this->openAPINullablesSetToNull, 'response');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('response', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['response'] = $response;

        return $this;
    }

    /**
     * Gets status_code
     *
     * @return \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress|null
     */
    public function getStatusCode()
    {
        return $this->container['status_code'];
    }

    /**
     * Sets status_code
     *
     * @param \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress|null $status_code status_code
     *
     * @return self
     */
    public function setStatusCode($status_code)
    {
        if (is_null($status_code)) {
            throw new \InvalidArgumentException('non-nullable status_code cannot be null');
        }
        $this->container['status_code'] = $status_code;

        return $this;
    }

    /**
     * Gets file_name
     *
     * @return string|null
     */
    public function getFileName()
    {
        return $this->container['file_name'];
    }

    /**
     * Sets file_name
     *
     * @param string|null $file_name file_name
     *
     * @return self
     */
    public function setFileName($file_name)
    {
        if (is_null($file_name)) {
            throw new \InvalidArgumentException('non-nullable file_name cannot be null');
        }
        $this->container['file_name'] = $file_name;

        return $this;
    }

    /**
     * Gets fecha_hora_anulacione_ncf
     *
     * @return \DateTime|null
     */
    public function getFechaHoraAnulacioneNcf()
    {
        return $this->container['fecha_hora_anulacione_ncf'];
    }

    /**
     * Sets fecha_hora_anulacione_ncf
     *
     * @param \DateTime|null $fecha_hora_anulacione_ncf fecha_hora_anulacione_ncf
     *
     * @return self
     */
    public function setFechaHoraAnulacioneNcf($fecha_hora_anulacione_ncf)
    {
        if (is_null($fecha_hora_anulacione_ncf)) {
            throw new \InvalidArgumentException('non-nullable fecha_hora_anulacione_ncf cannot be null');
        }
        $this->container['fecha_hora_anulacione_ncf'] = $fecha_hora_anulacione_ncf;

        return $this;
    }

    /**
     * Gets created_on
     *
     * @return \DateTime|null
     */
    public function getCreatedOn()
    {
        return $this->container['created_on'];
    }

    /**
     * Sets created_on
     *
     * @param \DateTime|null $created_on created_on
     *
     * @return self
     */
    public function setCreatedOn($created_on)
    {
        if (is_null($created_on)) {
            throw new \InvalidArgumentException('non-nullable created_on cannot be null');
        }
        $this->container['created_on'] = $created_on;

        return $this;
    }

    /**
     * Gets updated_on
     *
     * @return \DateTime|null
     */
    public function getUpdatedOn()
    {
        return $this->container['updated_on'];
    }

    /**
     * Sets updated_on
     *
     * @param \DateTime|null $updated_on updated_on
     *
     * @return self
     */
    public function setUpdatedOn($updated_on)
    {
        if (is_null($updated_on)) {
            throw new \InvalidArgumentException('non-nullable updated_on cannot be null');
        }
        $this->container['updated_on'] = $updated_on;

        return $this;
    }

    /**
     * Gets created_by
     *
     * @return string|null
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     *
     * @param string|null $created_by created_by
     *
     * @return self
     */
    public function setCreatedBy($created_by)
    {
        if (is_null($created_by)) {
            throw new \InvalidArgumentException('non-nullable created_by cannot be null');
        }
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets updated_by
     *
     * @return string|null
     */
    public function getUpdatedBy()
    {
        return $this->container['updated_by'];
    }

    /**
     * Sets updated_by
     *
     * @param string|null $updated_by updated_by
     *
     * @return self
     */
    public function setUpdatedBy($updated_by)
    {
        if (is_null($updated_by)) {
            throw new \InvalidArgumentException('non-nullable updated_by cannot be null');
        }
        $this->container['updated_by'] = $updated_by;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


