<?php
/**
 * DetalleAnulacionRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * DetalleAnulacionRequest Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DetalleAnulacionRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DetalleAnulacionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tipo_ecf' => '\Ecfx\EcfDgii\Model\ECFType',
        'cantidade_ncf_anulados' => '\Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress',
        'no_linea' => '\Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress[]',
        'secuencias' => '\Ecfx\EcfDgii\Model\SecuenciaRequest[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tipo_ecf' => null,
        'cantidade_ncf_anulados' => null,
        'no_linea' => null,
        'secuencias' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tipo_ecf' => false,
        'cantidade_ncf_anulados' => false,
        'no_linea' => false,
        'secuencias' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tipo_ecf' => 'tipoEcf',
        'cantidade_ncf_anulados' => 'cantidadeNcfAnulados',
        'no_linea' => 'noLinea',
        'secuencias' => 'secuencias'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tipo_ecf' => 'setTipoEcf',
        'cantidade_ncf_anulados' => 'setCantidadeNcfAnulados',
        'no_linea' => 'setNoLinea',
        'secuencias' => 'setSecuencias'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tipo_ecf' => 'getTipoEcf',
        'cantidade_ncf_anulados' => 'getCantidadeNcfAnulados',
        'no_linea' => 'getNoLinea',
        'secuencias' => 'getSecuencias'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tipo_ecf', $data ?? [], null);
        $this->setIfExists('cantidade_ncf_anulados', $data ?? [], null);
        $this->setIfExists('no_linea', $data ?? [], null);
        $this->setIfExists('secuencias', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tipo_ecf'] === null) {
            $invalidProperties[] = "'tipo_ecf' can't be null";
        }
        if ($this->container['cantidade_ncf_anulados'] === null) {
            $invalidProperties[] = "'cantidade_ncf_anulados' can't be null";
        }
        if ($this->container['no_linea'] === null) {
            $invalidProperties[] = "'no_linea' can't be null";
        }
        if ($this->container['secuencias'] === null) {
            $invalidProperties[] = "'secuencias' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tipo_ecf
     *
     * @return \Ecfx\EcfDgii\Model\ECFType
     */
    public function getTipoEcf()
    {
        return $this->container['tipo_ecf'];
    }

    /**
     * Sets tipo_ecf
     *
     * @param \Ecfx\EcfDgii\Model\ECFType $tipo_ecf tipo_ecf
     *
     * @return self
     */
    public function setTipoEcf($tipo_ecf)
    {
        if (is_null($tipo_ecf)) {
            throw new \InvalidArgumentException('non-nullable tipo_ecf cannot be null');
        }
        $this->container['tipo_ecf'] = $tipo_ecf;

        return $this;
    }

    /**
     * Gets cantidade_ncf_anulados
     *
     * @return \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress
     */
    public function getCantidadeNcfAnulados()
    {
        return $this->container['cantidade_ncf_anulados'];
    }

    /**
     * Sets cantidade_ncf_anulados
     *
     * @param \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress $cantidade_ncf_anulados cantidade_ncf_anulados
     *
     * @return self
     */
    public function setCantidadeNcfAnulados($cantidade_ncf_anulados)
    {
        if (is_null($cantidade_ncf_anulados)) {
            throw new \InvalidArgumentException('non-nullable cantidade_ncf_anulados cannot be null');
        }
        $this->container['cantidade_ncf_anulados'] = $cantidade_ncf_anulados;

        return $this;
    }

    /**
     * Gets no_linea
     *
     * @return \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress[]
     */
    public function getNoLinea()
    {
        return $this->container['no_linea'];
    }

    /**
     * Sets no_linea
     *
     * @param \Ecfx\EcfDgii\Model\AcecfReceptionRequestDtoProgress[] $no_linea no_linea
     *
     * @return self
     */
    public function setNoLinea($no_linea)
    {
        if (is_null($no_linea)) {
            throw new \InvalidArgumentException('non-nullable no_linea cannot be null');
        }
        $this->container['no_linea'] = $no_linea;

        return $this;
    }

    /**
     * Gets secuencias
     *
     * @return \Ecfx\EcfDgii\Model\SecuenciaRequest[]
     */
    public function getSecuencias()
    {
        return $this->container['secuencias'];
    }

    /**
     * Sets secuencias
     *
     * @param \Ecfx\EcfDgii\Model\SecuenciaRequest[] $secuencias secuencias
     *
     * @return self
     */
    public function setSecuencias($secuencias)
    {
        if (is_null($secuencias)) {
            throw new \InvalidArgumentException('non-nullable secuencias cannot be null');
        }
        $this->container['secuencias'] = $secuencias;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


