<?php
/**
 * Directorio
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * Directorio Class Doc Comment
 *
 * @category Class
 * @description Representa una entrada del directorio para contribuyentes electrónicos en el sistema de facturación electrónica  de la República Dominicana. Este modelo contiene las URLs de servicios que los contribuyentes electrónicos  deben proporcionar para la comunicación entre contribuyentes.
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Directorio implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Directorio';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'nombre' => 'string',
        'rnc' => 'string',
        'url_recepcion' => 'string',
        'url_aceptacion' => 'string',
        'url_opcional' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'nombre' => null,
        'rnc' => null,
        'url_recepcion' => null,
        'url_aceptacion' => null,
        'url_opcional' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'nombre' => true,
        'rnc' => true,
        'url_recepcion' => true,
        'url_aceptacion' => true,
        'url_opcional' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nombre' => 'nombre',
        'rnc' => 'rnc',
        'url_recepcion' => 'urlRecepcion',
        'url_aceptacion' => 'urlAceptacion',
        'url_opcional' => 'urlOpcional'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nombre' => 'setNombre',
        'rnc' => 'setRnc',
        'url_recepcion' => 'setUrlRecepcion',
        'url_aceptacion' => 'setUrlAceptacion',
        'url_opcional' => 'setUrlOpcional'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nombre' => 'getNombre',
        'rnc' => 'getRnc',
        'url_recepcion' => 'getUrlRecepcion',
        'url_aceptacion' => 'getUrlAceptacion',
        'url_opcional' => 'getUrlOpcional'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nombre', $data ?? [], null);
        $this->setIfExists('rnc', $data ?? [], null);
        $this->setIfExists('url_recepcion', $data ?? [], null);
        $this->setIfExists('url_aceptacion', $data ?? [], null);
        $this->setIfExists('url_opcional', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nombre
     *
     * @return string|null
     */
    public function getNombre()
    {
        return $this->container['nombre'];
    }

    /**
     * Sets nombre
     *
     * @param string|null $nombre Obtiene el nombre legal o razón social del contribuyente electrónico. La razón social registrada tal como aparece en el registro oficial del contribuyente. Este campo es requerido y debe coincidir con el nombre de la entidad legal del contribuyente.
     *
     * @return self
     */
    public function setNombre($nombre)
    {
        if (is_null($nombre)) {
            array_push($this->openAPINullablesSetToNull, 'nombre');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nombre', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nombre'] = $nombre;

        return $this;
    }

    /**
     * Gets rnc
     *
     * @return string|null
     */
    public function getRnc()
    {
        return $this->container['rnc'];
    }

    /**
     * Sets rnc
     *
     * @param string|null $rnc Obtiene el Número de Registro Nacional del Contribuyente (RNC) del contribuyente electrónico. Un número de 9 dígitos que identifica de forma única al contribuyente en el sistema tributario  de la República Dominicana. Este campo es requerido y debe tener un formato de RNC válido.
     *
     * @return self
     */
    public function setRnc($rnc)
    {
        if (is_null($rnc)) {
            array_push($this->openAPINullablesSetToNull, 'rnc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rnc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rnc'] = $rnc;

        return $this;
    }

    /**
     * Gets url_recepcion
     *
     * @return string|null
     */
    public function getUrlRecepcion()
    {
        return $this->container['url_recepcion'];
    }

    /**
     * Sets url_recepcion
     *
     * @param string|null $url_recepcion Obtiene la URL del servicio de recepción de facturas electrónicas. La URL completa donde otros contribuyentes pueden enviar facturas electrónicas (e-CF) a este contribuyente. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/recepcion/api/ecf Este campo es obligatorio para todos los contribuyentes electrónicos.
     *
     * @return self
     */
    public function setUrlRecepcion($url_recepcion)
    {
        if (is_null($url_recepcion)) {
            array_push($this->openAPINullablesSetToNull, 'url_recepcion');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url_recepcion', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url_recepcion'] = $url_recepcion;

        return $this;
    }

    /**
     * Gets url_aceptacion
     *
     * @return string|null
     */
    public function getUrlAceptacion()
    {
        return $this->container['url_aceptacion'];
    }

    /**
     * Sets url_aceptacion
     *
     * @param string|null $url_aceptacion Obtiene la URL del servicio de aprobación comercial. La URL completa donde otros contribuyentes pueden enviar aprobaciones comerciales para facturas recibidas. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/aprobacioncomercial/api/ecf Este campo es obligatorio para todos los contribuyentes electrónicos.
     *
     * @return self
     */
    public function setUrlAceptacion($url_aceptacion)
    {
        if (is_null($url_aceptacion)) {
            array_push($this->openAPINullablesSetToNull, 'url_aceptacion');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url_aceptacion', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url_aceptacion'] = $url_aceptacion;

        return $this;
    }

    /**
     * Gets url_opcional
     *
     * @return string|null
     */
    public function getUrlOpcional()
    {
        return $this->container['url_opcional'];
    }

    /**
     * Sets url_opcional
     *
     * @param string|null $url_opcional Obtiene la URL del servicio opcional de autenticación. La URL base del servicio de autenticación, si es implementado por el contribuyente. Debe seguir el formato estándar: https://host/ambiente/nombreservicio/fe/autenticacion/api/ Este campo es opcional pero recomendado para mayor seguridad.
     *
     * @return self
     */
    public function setUrlOpcional($url_opcional)
    {
        if (is_null($url_opcional)) {
            array_push($this->openAPINullablesSetToNull, 'url_opcional');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url_opcional', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url_opcional'] = $url_opcional;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


