<?php
/**
 * EcfResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * EcfResponse Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EcfResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EcfResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'message_id' => 'string',
        'timestamp' => '\DateTime',
        'fecha_emision' => '\DateTime',
        'queue_name' => 'string',
        'include_ecf_content' => 'bool',
        'ecf_content' => 'string',
        'tipo_ecf' => '\Ecfx\EcfDgii\Model\AllTipoECFTypes',
        'encf' => 'string',
        'rnc_emisor' => 'string',
        'rnc_receptor' => 'string',
        'monto_total' => '\Ecfx\EcfDgii\Model\SearchEcfsAmountFromParameter',
        'file_name' => 'string',
        'tenant_id' => 'string',
        'estatus' => '\Ecfx\EcfDgii\Model\EcfEstado',
        'cod_sec' => 'string',
        'fecha_firma' => '\DateTime',
        'mensaje' => 'string',
        'errors' => 'string',
        'progress' => '\Ecfx\EcfDgii\Model\EcfProgress',
        'emisor_receptor_errors' => 'string',
        'secuencia_utilizada' => 'bool',
        'dgii_environment' => '\Ecfx\EcfDgii\Model\DGIIEnvironment',
        'impresion_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'message_id' => 'uuid',
        'timestamp' => 'date-time',
        'fecha_emision' => 'date',
        'queue_name' => null,
        'include_ecf_content' => null,
        'ecf_content' => null,
        'tipo_ecf' => null,
        'encf' => null,
        'rnc_emisor' => null,
        'rnc_receptor' => null,
        'monto_total' => null,
        'file_name' => null,
        'tenant_id' => 'uuid',
        'estatus' => null,
        'cod_sec' => null,
        'fecha_firma' => 'date-time',
        'mensaje' => null,
        'errors' => null,
        'progress' => null,
        'emisor_receptor_errors' => null,
        'secuencia_utilizada' => null,
        'dgii_environment' => null,
        'impresion_url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'message_id' => false,
        'timestamp' => false,
        'fecha_emision' => false,
        'queue_name' => false,
        'include_ecf_content' => false,
        'ecf_content' => false,
        'tipo_ecf' => false,
        'encf' => false,
        'rnc_emisor' => false,
        'rnc_receptor' => true,
        'monto_total' => false,
        'file_name' => true,
        'tenant_id' => false,
        'estatus' => true,
        'cod_sec' => true,
        'fecha_firma' => true,
        'mensaje' => true,
        'errors' => true,
        'progress' => false,
        'emisor_receptor_errors' => true,
        'secuencia_utilizada' => true,
        'dgii_environment' => false,
        'impresion_url' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'message_id' => 'messageId',
        'timestamp' => 'timestamp',
        'fecha_emision' => 'fechaEmision',
        'queue_name' => 'queueName',
        'include_ecf_content' => 'includeEcfContent',
        'ecf_content' => 'ecfContent',
        'tipo_ecf' => 'tipoEcf',
        'encf' => 'encf',
        'rnc_emisor' => 'rncEmisor',
        'rnc_receptor' => 'rncReceptor',
        'monto_total' => 'montoTotal',
        'file_name' => 'fileName',
        'tenant_id' => 'tenantId',
        'estatus' => 'estatus',
        'cod_sec' => 'codSec',
        'fecha_firma' => 'fechaFirma',
        'mensaje' => 'mensaje',
        'errors' => 'errors',
        'progress' => 'progress',
        'emisor_receptor_errors' => 'emisorReceptorErrors',
        'secuencia_utilizada' => 'secuenciaUtilizada',
        'dgii_environment' => 'dgiiEnvironment',
        'impresion_url' => 'impresionUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'message_id' => 'setMessageId',
        'timestamp' => 'setTimestamp',
        'fecha_emision' => 'setFechaEmision',
        'queue_name' => 'setQueueName',
        'include_ecf_content' => 'setIncludeEcfContent',
        'ecf_content' => 'setEcfContent',
        'tipo_ecf' => 'setTipoEcf',
        'encf' => 'setEncf',
        'rnc_emisor' => 'setRncEmisor',
        'rnc_receptor' => 'setRncReceptor',
        'monto_total' => 'setMontoTotal',
        'file_name' => 'setFileName',
        'tenant_id' => 'setTenantId',
        'estatus' => 'setEstatus',
        'cod_sec' => 'setCodSec',
        'fecha_firma' => 'setFechaFirma',
        'mensaje' => 'setMensaje',
        'errors' => 'setErrors',
        'progress' => 'setProgress',
        'emisor_receptor_errors' => 'setEmisorReceptorErrors',
        'secuencia_utilizada' => 'setSecuenciaUtilizada',
        'dgii_environment' => 'setDgiiEnvironment',
        'impresion_url' => 'setImpresionUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'message_id' => 'getMessageId',
        'timestamp' => 'getTimestamp',
        'fecha_emision' => 'getFechaEmision',
        'queue_name' => 'getQueueName',
        'include_ecf_content' => 'getIncludeEcfContent',
        'ecf_content' => 'getEcfContent',
        'tipo_ecf' => 'getTipoEcf',
        'encf' => 'getEncf',
        'rnc_emisor' => 'getRncEmisor',
        'rnc_receptor' => 'getRncReceptor',
        'monto_total' => 'getMontoTotal',
        'file_name' => 'getFileName',
        'tenant_id' => 'getTenantId',
        'estatus' => 'getEstatus',
        'cod_sec' => 'getCodSec',
        'fecha_firma' => 'getFechaFirma',
        'mensaje' => 'getMensaje',
        'errors' => 'getErrors',
        'progress' => 'getProgress',
        'emisor_receptor_errors' => 'getEmisorReceptorErrors',
        'secuencia_utilizada' => 'getSecuenciaUtilizada',
        'dgii_environment' => 'getDgiiEnvironment',
        'impresion_url' => 'getImpresionUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('message_id', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('fecha_emision', $data ?? [], null);
        $this->setIfExists('queue_name', $data ?? [], null);
        $this->setIfExists('include_ecf_content', $data ?? [], null);
        $this->setIfExists('ecf_content', $data ?? [], null);
        $this->setIfExists('tipo_ecf', $data ?? [], null);
        $this->setIfExists('encf', $data ?? [], null);
        $this->setIfExists('rnc_emisor', $data ?? [], null);
        $this->setIfExists('rnc_receptor', $data ?? [], null);
        $this->setIfExists('monto_total', $data ?? [], null);
        $this->setIfExists('file_name', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('estatus', $data ?? [], null);
        $this->setIfExists('cod_sec', $data ?? [], null);
        $this->setIfExists('fecha_firma', $data ?? [], null);
        $this->setIfExists('mensaje', $data ?? [], null);
        $this->setIfExists('errors', $data ?? [], null);
        $this->setIfExists('progress', $data ?? [], null);
        $this->setIfExists('emisor_receptor_errors', $data ?? [], null);
        $this->setIfExists('secuencia_utilizada', $data ?? [], null);
        $this->setIfExists('dgii_environment', $data ?? [], null);
        $this->setIfExists('impresion_url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['message_id'] === null) {
            $invalidProperties[] = "'message_id' can't be null";
        }
        if ($this->container['timestamp'] === null) {
            $invalidProperties[] = "'timestamp' can't be null";
        }
        if ($this->container['fecha_emision'] === null) {
            $invalidProperties[] = "'fecha_emision' can't be null";
        }
        if ($this->container['queue_name'] === null) {
            $invalidProperties[] = "'queue_name' can't be null";
        }
        if ($this->container['include_ecf_content'] === null) {
            $invalidProperties[] = "'include_ecf_content' can't be null";
        }
        if ($this->container['ecf_content'] === null) {
            $invalidProperties[] = "'ecf_content' can't be null";
        }
        if ($this->container['tipo_ecf'] === null) {
            $invalidProperties[] = "'tipo_ecf' can't be null";
        }
        if ($this->container['encf'] === null) {
            $invalidProperties[] = "'encf' can't be null";
        }
        if ($this->container['rnc_emisor'] === null) {
            $invalidProperties[] = "'rnc_emisor' can't be null";
        }
        if ($this->container['rnc_receptor'] === null && !$this->isNullableSetToNull('rnc_receptor')) {
            $invalidProperties[] = "'rnc_receptor' can't be null";
        }
        if ($this->container['monto_total'] === null) {
            $invalidProperties[] = "'monto_total' can't be null";
        }
        if ($this->container['file_name'] === null && !$this->isNullableSetToNull('file_name')) {
            $invalidProperties[] = "'file_name' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if ($this->container['estatus'] === null && !$this->isNullableSetToNull('estatus')) {
            $invalidProperties[] = "'estatus' can't be null";
        }
        if ($this->container['cod_sec'] === null && !$this->isNullableSetToNull('cod_sec')) {
            $invalidProperties[] = "'cod_sec' can't be null";
        }
        if ($this->container['fecha_firma'] === null && !$this->isNullableSetToNull('fecha_firma')) {
            $invalidProperties[] = "'fecha_firma' can't be null";
        }
        if ($this->container['mensaje'] === null && !$this->isNullableSetToNull('mensaje')) {
            $invalidProperties[] = "'mensaje' can't be null";
        }
        if ($this->container['errors'] === null && !$this->isNullableSetToNull('errors')) {
            $invalidProperties[] = "'errors' can't be null";
        }
        if ($this->container['progress'] === null) {
            $invalidProperties[] = "'progress' can't be null";
        }
        if ($this->container['emisor_receptor_errors'] === null && !$this->isNullableSetToNull('emisor_receptor_errors')) {
            $invalidProperties[] = "'emisor_receptor_errors' can't be null";
        }
        if ($this->container['secuencia_utilizada'] === null && !$this->isNullableSetToNull('secuencia_utilizada')) {
            $invalidProperties[] = "'secuencia_utilizada' can't be null";
        }
        if ($this->container['dgii_environment'] === null) {
            $invalidProperties[] = "'dgii_environment' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets message_id
     *
     * @return string
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param string $message_id message_id
     *
     * @return self
     */
    public function setMessageId($message_id)
    {
        if (is_null($message_id)) {
            throw new \InvalidArgumentException('non-nullable message_id cannot be null');
        }
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime $timestamp timestamp
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets fecha_emision
     *
     * @return \DateTime
     */
    public function getFechaEmision()
    {
        return $this->container['fecha_emision'];
    }

    /**
     * Sets fecha_emision
     *
     * @param \DateTime $fecha_emision fecha_emision
     *
     * @return self
     */
    public function setFechaEmision($fecha_emision)
    {
        if (is_null($fecha_emision)) {
            throw new \InvalidArgumentException('non-nullable fecha_emision cannot be null');
        }
        $this->container['fecha_emision'] = $fecha_emision;

        return $this;
    }

    /**
     * Gets queue_name
     *
     * @return string
     */
    public function getQueueName()
    {
        return $this->container['queue_name'];
    }

    /**
     * Sets queue_name
     *
     * @param string $queue_name queue_name
     *
     * @return self
     */
    public function setQueueName($queue_name)
    {
        if (is_null($queue_name)) {
            throw new \InvalidArgumentException('non-nullable queue_name cannot be null');
        }
        $this->container['queue_name'] = $queue_name;

        return $this;
    }

    /**
     * Gets include_ecf_content
     *
     * @return bool
     */
    public function getIncludeEcfContent()
    {
        return $this->container['include_ecf_content'];
    }

    /**
     * Sets include_ecf_content
     *
     * @param bool $include_ecf_content include_ecf_content
     *
     * @return self
     */
    public function setIncludeEcfContent($include_ecf_content)
    {
        if (is_null($include_ecf_content)) {
            throw new \InvalidArgumentException('non-nullable include_ecf_content cannot be null');
        }
        $this->container['include_ecf_content'] = $include_ecf_content;

        return $this;
    }

    /**
     * Gets ecf_content
     *
     * @return string
     */
    public function getEcfContent()
    {
        return $this->container['ecf_content'];
    }

    /**
     * Sets ecf_content
     *
     * @param string $ecf_content ecf_content
     *
     * @return self
     */
    public function setEcfContent($ecf_content)
    {
        if (is_null($ecf_content)) {
            throw new \InvalidArgumentException('non-nullable ecf_content cannot be null');
        }
        $this->container['ecf_content'] = $ecf_content;

        return $this;
    }

    /**
     * Gets tipo_ecf
     *
     * @return \Ecfx\EcfDgii\Model\AllTipoECFTypes
     */
    public function getTipoEcf()
    {
        return $this->container['tipo_ecf'];
    }

    /**
     * Sets tipo_ecf
     *
     * @param \Ecfx\EcfDgii\Model\AllTipoECFTypes $tipo_ecf tipo_ecf
     *
     * @return self
     */
    public function setTipoEcf($tipo_ecf)
    {
        if (is_null($tipo_ecf)) {
            throw new \InvalidArgumentException('non-nullable tipo_ecf cannot be null');
        }
        $this->container['tipo_ecf'] = $tipo_ecf;

        return $this;
    }

    /**
     * Gets encf
     *
     * @return string
     */
    public function getEncf()
    {
        return $this->container['encf'];
    }

    /**
     * Sets encf
     *
     * @param string $encf encf
     *
     * @return self
     */
    public function setEncf($encf)
    {
        if (is_null($encf)) {
            throw new \InvalidArgumentException('non-nullable encf cannot be null');
        }
        $this->container['encf'] = $encf;

        return $this;
    }

    /**
     * Gets rnc_emisor
     *
     * @return string
     */
    public function getRncEmisor()
    {
        return $this->container['rnc_emisor'];
    }

    /**
     * Sets rnc_emisor
     *
     * @param string $rnc_emisor rnc_emisor
     *
     * @return self
     */
    public function setRncEmisor($rnc_emisor)
    {
        if (is_null($rnc_emisor)) {
            throw new \InvalidArgumentException('non-nullable rnc_emisor cannot be null');
        }
        $this->container['rnc_emisor'] = $rnc_emisor;

        return $this;
    }

    /**
     * Gets rnc_receptor
     *
     * @return string|null
     */
    public function getRncReceptor()
    {
        return $this->container['rnc_receptor'];
    }

    /**
     * Sets rnc_receptor
     *
     * @param string|null $rnc_receptor rnc_receptor
     *
     * @return self
     */
    public function setRncReceptor($rnc_receptor)
    {
        if (is_null($rnc_receptor)) {
            array_push($this->openAPINullablesSetToNull, 'rnc_receptor');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rnc_receptor', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rnc_receptor'] = $rnc_receptor;

        return $this;
    }

    /**
     * Gets monto_total
     *
     * @return \Ecfx\EcfDgii\Model\SearchEcfsAmountFromParameter
     */
    public function getMontoTotal()
    {
        return $this->container['monto_total'];
    }

    /**
     * Sets monto_total
     *
     * @param \Ecfx\EcfDgii\Model\SearchEcfsAmountFromParameter $monto_total monto_total
     *
     * @return self
     */
    public function setMontoTotal($monto_total)
    {
        if (is_null($monto_total)) {
            throw new \InvalidArgumentException('non-nullable monto_total cannot be null');
        }
        $this->container['monto_total'] = $monto_total;

        return $this;
    }

    /**
     * Gets file_name
     *
     * @return string|null
     */
    public function getFileName()
    {
        return $this->container['file_name'];
    }

    /**
     * Sets file_name
     *
     * @param string|null $file_name file_name
     *
     * @return self
     */
    public function setFileName($file_name)
    {
        if (is_null($file_name)) {
            array_push($this->openAPINullablesSetToNull, 'file_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('file_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['file_name'] = $file_name;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets estatus
     *
     * @return \Ecfx\EcfDgii\Model\EcfEstado|null
     */
    public function getEstatus()
    {
        return $this->container['estatus'];
    }

    /**
     * Sets estatus
     *
     * @param \Ecfx\EcfDgii\Model\EcfEstado|null $estatus estatus
     *
     * @return self
     */
    public function setEstatus($estatus)
    {
        if (is_null($estatus)) {
            array_push($this->openAPINullablesSetToNull, 'estatus');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estatus', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['estatus'] = $estatus;

        return $this;
    }

    /**
     * Gets cod_sec
     *
     * @return string|null
     */
    public function getCodSec()
    {
        return $this->container['cod_sec'];
    }

    /**
     * Sets cod_sec
     *
     * @param string|null $cod_sec cod_sec
     *
     * @return self
     */
    public function setCodSec($cod_sec)
    {
        if (is_null($cod_sec)) {
            array_push($this->openAPINullablesSetToNull, 'cod_sec');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cod_sec', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cod_sec'] = $cod_sec;

        return $this;
    }

    /**
     * Gets fecha_firma
     *
     * @return \DateTime|null
     */
    public function getFechaFirma()
    {
        return $this->container['fecha_firma'];
    }

    /**
     * Sets fecha_firma
     *
     * @param \DateTime|null $fecha_firma fecha_firma
     *
     * @return self
     */
    public function setFechaFirma($fecha_firma)
    {
        if (is_null($fecha_firma)) {
            array_push($this->openAPINullablesSetToNull, 'fecha_firma');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fecha_firma', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fecha_firma'] = $fecha_firma;

        return $this;
    }

    /**
     * Gets mensaje
     *
     * @return string|null
     */
    public function getMensaje()
    {
        return $this->container['mensaje'];
    }

    /**
     * Sets mensaje
     *
     * @param string|null $mensaje mensaje
     *
     * @return self
     */
    public function setMensaje($mensaje)
    {
        if (is_null($mensaje)) {
            array_push($this->openAPINullablesSetToNull, 'mensaje');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mensaje', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mensaje'] = $mensaje;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return string|null
     */
    public function getErrors()
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param string|null $errors errors
     *
     * @return self
     */
    public function setErrors($errors)
    {
        if (is_null($errors)) {
            array_push($this->openAPINullablesSetToNull, 'errors');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('errors', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['errors'] = $errors;

        return $this;
    }

    /**
     * Gets progress
     *
     * @return \Ecfx\EcfDgii\Model\EcfProgress
     */
    public function getProgress()
    {
        return $this->container['progress'];
    }

    /**
     * Sets progress
     *
     * @param \Ecfx\EcfDgii\Model\EcfProgress $progress progress
     *
     * @return self
     */
    public function setProgress($progress)
    {
        if (is_null($progress)) {
            throw new \InvalidArgumentException('non-nullable progress cannot be null');
        }
        $this->container['progress'] = $progress;

        return $this;
    }

    /**
     * Gets emisor_receptor_errors
     *
     * @return string|null
     */
    public function getEmisorReceptorErrors()
    {
        return $this->container['emisor_receptor_errors'];
    }

    /**
     * Sets emisor_receptor_errors
     *
     * @param string|null $emisor_receptor_errors emisor_receptor_errors
     *
     * @return self
     */
    public function setEmisorReceptorErrors($emisor_receptor_errors)
    {
        if (is_null($emisor_receptor_errors)) {
            array_push($this->openAPINullablesSetToNull, 'emisor_receptor_errors');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('emisor_receptor_errors', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['emisor_receptor_errors'] = $emisor_receptor_errors;

        return $this;
    }

    /**
     * Gets secuencia_utilizada
     *
     * @return bool|null
     */
    public function getSecuenciaUtilizada()
    {
        return $this->container['secuencia_utilizada'];
    }

    /**
     * Sets secuencia_utilizada
     *
     * @param bool|null $secuencia_utilizada secuencia_utilizada
     *
     * @return self
     */
    public function setSecuenciaUtilizada($secuencia_utilizada)
    {
        if (is_null($secuencia_utilizada)) {
            array_push($this->openAPINullablesSetToNull, 'secuencia_utilizada');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('secuencia_utilizada', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['secuencia_utilizada'] = $secuencia_utilizada;

        return $this;
    }

    /**
     * Gets dgii_environment
     *
     * @return \Ecfx\EcfDgii\Model\DGIIEnvironment
     */
    public function getDgiiEnvironment()
    {
        return $this->container['dgii_environment'];
    }

    /**
     * Sets dgii_environment
     *
     * @param \Ecfx\EcfDgii\Model\DGIIEnvironment $dgii_environment dgii_environment
     *
     * @return self
     */
    public function setDgiiEnvironment($dgii_environment)
    {
        if (is_null($dgii_environment)) {
            throw new \InvalidArgumentException('non-nullable dgii_environment cannot be null');
        }
        $this->container['dgii_environment'] = $dgii_environment;

        return $this;
    }

    /**
     * Gets impresion_url
     *
     * @return string|null
     */
    public function getImpresionUrl()
    {
        return $this->container['impresion_url'];
    }

    /**
     * Sets impresion_url
     *
     * @param string|null $impresion_url impresion_url
     *
     * @return self
     */
    public function setImpresionUrl($impresion_url)
    {
        if (is_null($impresion_url)) {
            array_push($this->openAPINullablesSetToNull, 'impresion_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('impresion_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['impresion_url'] = $impresion_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


