<?php
/**
 * ECFType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * ECFType Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ECFType
{
    /**
     * Possible values of this enum
     */
    public const ECF31 = 'ECF31';

    public const ECF32 = 'ECF32';

    public const ECF33 = 'ECF33';

    public const ECF34 = 'ECF34';

    public const ECF41 = 'ECF41';

    public const ECF43 = 'ECF43';

    public const ECF44 = 'ECF44';

    public const ECF45 = 'ECF45';

    public const ECF46 = 'ECF46';

    public const ECF47 = 'ECF47';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ECF31,
            self::ECF32,
            self::ECF33,
            self::ECF34,
            self::ECF41,
            self::ECF43,
            self::ECF44,
            self::ECF45,
            self::ECF46,
            self::ECF47
        ];
    }
}


