<?php
/**
 * IndicadorServicioTodoIncluidoType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * IndicadorServicioTodoIncluidoType Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IndicadorServicioTodoIncluidoType
{
    /**
     * Possible values of this enum
     */
    public const INDICADOR_SERVICIO_TODO_INCLUIDO = 'IndicadorServicioTodoIncluido';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INDICADOR_SERVICIO_TODO_INCLUIDO
        ];
    }
}


