<?php
/**
 * IndicadorMontoGravadoType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * IndicadorMontoGravadoType Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IndicadorMontoGravadoType
{
    /**
     * Possible values of this enum
     */
    public const SIN_ITBIS_INCLUIDO = 'SinITBISIncluido';

    public const CON_ITBIS_INCLUIDO = 'ConITBISIncluido';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SIN_ITBIS_INCLUIDO,
            self::CON_ITBIS_INCLUIDO
        ];
    }
}


