<?php
/**
 * RespuestaConsultaEstado
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * RespuestaConsultaEstado Class Doc Comment
 *
 * @category Class
 * @description Representa la respuesta del servicio de consulta de estado de e-CF. Este modelo contiene la información de validez y estado de un comprobante fiscal electrónico consultado a través del servicio web de consulta estado de la DGII.
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RespuestaConsultaEstado implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RespuestaConsultaEstado';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'codigo' => '\Ecfx\EcfDgii\Model\RespuestaConsultaEstadoCodigo',
        'estado' => 'string',
        'rnc_emisor' => 'string',
        'ncf_electronico' => 'string',
        'monto_total' => '\Ecfx\EcfDgii\Model\RespuestaConsultaEstadoMontoTotal',
        'total_itbis' => '\Ecfx\EcfDgii\Model\RespuestaConsultaEstadoTotalITBIS',
        'fecha_emision' => 'string',
        'fecha_firma' => 'string',
        'rnc_comprador' => 'string',
        'codigo_seguridad' => 'string',
        'id_extranjero' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'codigo' => null,
        'estado' => null,
        'rnc_emisor' => null,
        'ncf_electronico' => null,
        'monto_total' => null,
        'total_itbis' => null,
        'fecha_emision' => null,
        'fecha_firma' => null,
        'rnc_comprador' => null,
        'codigo_seguridad' => null,
        'id_extranjero' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'codigo' => false,
        'estado' => true,
        'rnc_emisor' => true,
        'ncf_electronico' => true,
        'monto_total' => true,
        'total_itbis' => true,
        'fecha_emision' => true,
        'fecha_firma' => true,
        'rnc_comprador' => true,
        'codigo_seguridad' => true,
        'id_extranjero' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'codigo' => 'codigo',
        'estado' => 'estado',
        'rnc_emisor' => 'rncEmisor',
        'ncf_electronico' => 'ncfElectronico',
        'monto_total' => 'montoTotal',
        'total_itbis' => 'totalITBIS',
        'fecha_emision' => 'fechaEmision',
        'fecha_firma' => 'fechaFirma',
        'rnc_comprador' => 'rncComprador',
        'codigo_seguridad' => 'codigoSeguridad',
        'id_extranjero' => 'idExtranjero'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'codigo' => 'setCodigo',
        'estado' => 'setEstado',
        'rnc_emisor' => 'setRncEmisor',
        'ncf_electronico' => 'setNcfElectronico',
        'monto_total' => 'setMontoTotal',
        'total_itbis' => 'setTotalItbis',
        'fecha_emision' => 'setFechaEmision',
        'fecha_firma' => 'setFechaFirma',
        'rnc_comprador' => 'setRncComprador',
        'codigo_seguridad' => 'setCodigoSeguridad',
        'id_extranjero' => 'setIdExtranjero'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'codigo' => 'getCodigo',
        'estado' => 'getEstado',
        'rnc_emisor' => 'getRncEmisor',
        'ncf_electronico' => 'getNcfElectronico',
        'monto_total' => 'getMontoTotal',
        'total_itbis' => 'getTotalItbis',
        'fecha_emision' => 'getFechaEmision',
        'fecha_firma' => 'getFechaFirma',
        'rnc_comprador' => 'getRncComprador',
        'codigo_seguridad' => 'getCodigoSeguridad',
        'id_extranjero' => 'getIdExtranjero'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('codigo', $data ?? [], null);
        $this->setIfExists('estado', $data ?? [], null);
        $this->setIfExists('rnc_emisor', $data ?? [], null);
        $this->setIfExists('ncf_electronico', $data ?? [], null);
        $this->setIfExists('monto_total', $data ?? [], null);
        $this->setIfExists('total_itbis', $data ?? [], null);
        $this->setIfExists('fecha_emision', $data ?? [], null);
        $this->setIfExists('fecha_firma', $data ?? [], null);
        $this->setIfExists('rnc_comprador', $data ?? [], null);
        $this->setIfExists('codigo_seguridad', $data ?? [], null);
        $this->setIfExists('id_extranjero', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets codigo
     *
     * @return \Ecfx\EcfDgii\Model\RespuestaConsultaEstadoCodigo|null
     */
    public function getCodigo()
    {
        return $this->container['codigo'];
    }

    /**
     * Sets codigo
     *
     * @param \Ecfx\EcfDgii\Model\RespuestaConsultaEstadoCodigo|null $codigo codigo
     *
     * @return self
     */
    public function setCodigo($codigo)
    {
        if (is_null($codigo)) {
            throw new \InvalidArgumentException('non-nullable codigo cannot be null');
        }
        $this->container['codigo'] = $codigo;

        return $this;
    }

    /**
     * Gets estado
     *
     * @return string|null
     */
    public function getEstado()
    {
        return $this->container['estado'];
    }

    /**
     * Sets estado
     *
     * @param string|null $estado Estado de validación otorgado por Impuestos Internos al e-CF recibido. Descripción textual del estado del comprobante fiscal electrónico.
     *
     * @return self
     */
    public function setEstado($estado)
    {
        if (is_null($estado)) {
            array_push($this->openAPINullablesSetToNull, 'estado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['estado'] = $estado;

        return $this;
    }

    /**
     * Gets rnc_emisor
     *
     * @return string|null
     */
    public function getRncEmisor()
    {
        return $this->container['rnc_emisor'];
    }

    /**
     * Sets rnc_emisor
     *
     * @param string|null $rnc_emisor Número de registro nacional del contribuyente que envió el e-CF. RNC del emisor del comprobante fiscal electrónico.
     *
     * @return self
     */
    public function setRncEmisor($rnc_emisor)
    {
        if (is_null($rnc_emisor)) {
            array_push($this->openAPINullablesSetToNull, 'rnc_emisor');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rnc_emisor', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rnc_emisor'] = $rnc_emisor;

        return $this;
    }

    /**
     * Gets ncf_electronico
     *
     * @return string|null
     */
    public function getNcfElectronico()
    {
        return $this->container['ncf_electronico'];
    }

    /**
     * Sets ncf_electronico
     *
     * @param string|null $ncf_electronico Número de secuencia utilizada por el contribuyente en el e-CF. Número de comprobante fiscal electrónico (e-NCF) utilizado en la transacción.
     *
     * @return self
     */
    public function setNcfElectronico($ncf_electronico)
    {
        if (is_null($ncf_electronico)) {
            array_push($this->openAPINullablesSetToNull, 'ncf_electronico');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ncf_electronico', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ncf_electronico'] = $ncf_electronico;

        return $this;
    }

    /**
     * Gets monto_total
     *
     * @return \Ecfx\EcfDgii\Model\RespuestaConsultaEstadoMontoTotal|null
     */
    public function getMontoTotal()
    {
        return $this->container['monto_total'];
    }

    /**
     * Sets monto_total
     *
     * @param \Ecfx\EcfDgii\Model\RespuestaConsultaEstadoMontoTotal|null $monto_total monto_total
     *
     * @return self
     */
    public function setMontoTotal($monto_total)
    {
        if (is_null($monto_total)) {
            array_push($this->openAPINullablesSetToNull, 'monto_total');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('monto_total', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['monto_total'] = $monto_total;

        return $this;
    }

    /**
     * Gets total_itbis
     *
     * @return \Ecfx\EcfDgii\Model\RespuestaConsultaEstadoTotalITBIS|null
     */
    public function getTotalItbis()
    {
        return $this->container['total_itbis'];
    }

    /**
     * Sets total_itbis
     *
     * @param \Ecfx\EcfDgii\Model\RespuestaConsultaEstadoTotalITBIS|null $total_itbis total_itbis
     *
     * @return self
     */
    public function setTotalItbis($total_itbis)
    {
        if (is_null($total_itbis)) {
            array_push($this->openAPINullablesSetToNull, 'total_itbis');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_itbis', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_itbis'] = $total_itbis;

        return $this;
    }

    /**
     * Gets fecha_emision
     *
     * @return string|null
     */
    public function getFechaEmision()
    {
        return $this->container['fecha_emision'];
    }

    /**
     * Sets fecha_emision
     *
     * @param string|null $fecha_emision Fecha de emisión extraída del e-CF recibido. Fecha en que fue emitido el comprobante fiscal electrónico.
     *
     * @return self
     */
    public function setFechaEmision($fecha_emision)
    {
        if (is_null($fecha_emision)) {
            array_push($this->openAPINullablesSetToNull, 'fecha_emision');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fecha_emision', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fecha_emision'] = $fecha_emision;

        return $this;
    }

    /**
     * Gets fecha_firma
     *
     * @return string|null
     */
    public function getFechaFirma()
    {
        return $this->container['fecha_firma'];
    }

    /**
     * Sets fecha_firma
     *
     * @param string|null $fecha_firma Fecha de firma extraída del e-CF recibido. Fecha en que fue firmado digitalmente el comprobante fiscal electrónico.
     *
     * @return self
     */
    public function setFechaFirma($fecha_firma)
    {
        if (is_null($fecha_firma)) {
            array_push($this->openAPINullablesSetToNull, 'fecha_firma');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fecha_firma', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fecha_firma'] = $fecha_firma;

        return $this;
    }

    /**
     * Gets rnc_comprador
     *
     * @return string|null
     */
    public function getRncComprador()
    {
        return $this->container['rnc_comprador'];
    }

    /**
     * Sets rnc_comprador
     *
     * @param string|null $rnc_comprador RNC del comprador extraído del e-CF recibido (si aplica). Número de registro nacional del contribuyente comprador, cuando corresponde.
     *
     * @return self
     */
    public function setRncComprador($rnc_comprador)
    {
        if (is_null($rnc_comprador)) {
            array_push($this->openAPINullablesSetToNull, 'rnc_comprador');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rnc_comprador', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rnc_comprador'] = $rnc_comprador;

        return $this;
    }

    /**
     * Gets codigo_seguridad
     *
     * @return string|null
     */
    public function getCodigoSeguridad()
    {
        return $this->container['codigo_seguridad'];
    }

    /**
     * Sets codigo_seguridad
     *
     * @param string|null $codigo_seguridad Código de seguridad extraído de los primeros seis (6) dígitos del hash generado  en el SignatureValue de la firma digital del e-CF recibido. Código de seguridad de 6 caracteres para validación del comprobante.
     *
     * @return self
     */
    public function setCodigoSeguridad($codigo_seguridad)
    {
        if (is_null($codigo_seguridad)) {
            array_push($this->openAPINullablesSetToNull, 'codigo_seguridad');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codigo_seguridad', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codigo_seguridad'] = $codigo_seguridad;

        return $this;
    }

    /**
     * Gets id_extranjero
     *
     * @return string|null
     */
    public function getIdExtranjero()
    {
        return $this->container['id_extranjero'];
    }

    /**
     * Sets id_extranjero
     *
     * @param string|null $id_extranjero Identificación de extranjero extraída del e-CF recibido (si aplica). Número de identificación del comprador extranjero cuando corresponde.
     *
     * @return self
     */
    public function setIdExtranjero($id_extranjero)
    {
        if (is_null($id_extranjero)) {
            array_push($this->openAPINullablesSetToNull, 'id_extranjero');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_extranjero', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id_extranjero'] = $id_extranjero;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


