<?php
/**
 * RespuestaConsultaRFCE
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;

use \ArrayAccess;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * RespuestaConsultaRFCE Class Doc Comment
 *
 * @category Class
 * @description Representa la respuesta del servicio de Consulta de Resumen de Factura (RFCE) de la DGII. Este servicio permite validar la validez fiscal de un comprobante fiscal electrónico a través del RNC emisor, e-NCF y código de seguridad.
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RespuestaConsultaRFCE implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RespuestaConsultaRFCE';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rnc' => 'string',
        'encf' => 'string',
        'secuencia_utilizada' => 'bool',
        'codigo' => 'string',
        'estado' => 'string',
        'mensajes' => '\Ecfx\EcfDgii\Model\Mensaje[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rnc' => null,
        'encf' => null,
        'secuencia_utilizada' => null,
        'codigo' => null,
        'estado' => null,
        'mensajes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rnc' => true,
        'encf' => false,
        'secuencia_utilizada' => false,
        'codigo' => true,
        'estado' => true,
        'mensajes' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rnc' => 'rnc',
        'encf' => 'encf',
        'secuencia_utilizada' => 'secuenciaUtilizada',
        'codigo' => 'codigo',
        'estado' => 'estado',
        'mensajes' => 'mensajes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rnc' => 'setRnc',
        'encf' => 'setEncf',
        'secuencia_utilizada' => 'setSecuenciaUtilizada',
        'codigo' => 'setCodigo',
        'estado' => 'setEstado',
        'mensajes' => 'setMensajes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rnc' => 'getRnc',
        'encf' => 'getEncf',
        'secuencia_utilizada' => 'getSecuenciaUtilizada',
        'codigo' => 'getCodigo',
        'estado' => 'getEstado',
        'mensajes' => 'getMensajes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rnc', $data ?? [], null);
        $this->setIfExists('encf', $data ?? [], null);
        $this->setIfExists('secuencia_utilizada', $data ?? [], null);
        $this->setIfExists('codigo', $data ?? [], null);
        $this->setIfExists('estado', $data ?? [], null);
        $this->setIfExists('mensajes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rnc
     *
     * @return string|null
     */
    public function getRnc()
    {
        return $this->container['rnc'];
    }

    /**
     * Sets rnc
     *
     * @param string|null $rnc Número de registro nacional del contribuyente que envió el e-CF. RNC del emisor del comprobante fiscal electrónico consultado.
     *
     * @return self
     */
    public function setRnc($rnc)
    {
        if (is_null($rnc)) {
            array_push($this->openAPINullablesSetToNull, 'rnc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rnc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rnc'] = $rnc;

        return $this;
    }

    /**
     * Gets encf
     *
     * @return string|null
     */
    public function getEncf()
    {
        return $this->container['encf'];
    }

    /**
     * Sets encf
     *
     * @param string|null $encf Número de secuencia utilizada por el contribuyente en el ENCF. Número de comprobante fiscal electrónico (e-NCF) consultado.
     *
     * @return self
     */
    public function setEncf($encf)
    {
        if (is_null($encf)) {
            throw new \InvalidArgumentException('non-nullable encf cannot be null');
        }
        $this->container['encf'] = $encf;

        return $this;
    }

    /**
     * Gets secuencia_utilizada
     *
     * @return bool|null
     */
    public function getSecuenciaUtilizada()
    {
        return $this->container['secuencia_utilizada'];
    }

    /**
     * Sets secuencia_utilizada
     *
     * @param bool|null $secuencia_utilizada Indica si el número de secuencia puede ser reutilizado. `true` si la secuencia NO puede reutilizarse (rechazado por motivos específicos);         `false` si la secuencia SÍ puede reutilizarse.
     *
     * @return self
     */
    public function setSecuenciaUtilizada($secuencia_utilizada)
    {
        if (is_null($secuencia_utilizada)) {
            throw new \InvalidArgumentException('non-nullable secuencia_utilizada cannot be null');
        }
        $this->container['secuencia_utilizada'] = $secuencia_utilizada;

        return $this;
    }

    /**
     * Gets codigo
     *
     * @return string|null
     */
    public function getCodigo()
    {
        return $this->container['codigo'];
    }

    /**
     * Sets codigo
     *
     * @param string|null $codigo Código asociado al estado de validación del e-CF recibido. Código numérico que indica el resultado de la validación: - 0: No encontrado - 1: Aceptado - 2: Rechazado - 4: Aceptado Condicional (solo para FC &lt; RD$ 250000.00)
     *
     * @return self
     */
    public function setCodigo($codigo)
    {
        if (is_null($codigo)) {
            array_push($this->openAPINullablesSetToNull, 'codigo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('codigo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['codigo'] = $codigo;

        return $this;
    }

    /**
     * Gets estado
     *
     * @return string|null
     */
    public function getEstado()
    {
        return $this->container['estado'];
    }

    /**
     * Sets estado
     *
     * @param string|null $estado Estado de validación otorgado por Impuestos Internos al e-CF recibido. Descripción textual del estado de validación del comprobante.
     *
     * @return self
     */
    public function setEstado($estado)
    {
        if (is_null($estado)) {
            array_push($this->openAPINullablesSetToNull, 'estado');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estado', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['estado'] = $estado;

        return $this;
    }

    /**
     * Gets mensajes
     *
     * @return \Ecfx\EcfDgii\Model\Mensaje[]|null
     */
    public function getMensajes()
    {
        return $this->container['mensajes'];
    }

    /**
     * Sets mensajes
     *
     * @param \Ecfx\EcfDgii\Model\Mensaje[]|null $mensajes Mensajes y códigos asociados al estado de validación del e-CF recibido. Array de mensajes que proporcionan detalles adicionales sobre la validación.
     *
     * @return self
     */
    public function setMensajes($mensajes)
    {
        if (is_null($mensajes)) {
            array_push($this->openAPINullablesSetToNull, 'mensajes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mensajes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mensajes'] = $mensajes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


