<?php
/**
 * TipoMonedaType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * TipoMonedaType Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TipoMonedaType
{
    /**
     * Possible values of this enum
     */
    public const BRL = 'BRL';

    public const CAD = 'CAD';

    public const CHF = 'CHF';

    public const CHY = 'CHY';

    public const XDR = 'XDR';

    public const DKK = 'DKK';

    public const EUR = 'EUR';

    public const GBP = 'GBP';

    public const JPY = 'JPY';

    public const NOK = 'NOK';

    public const SCP = 'SCP';

    public const SEK = 'SEK';

    public const USD = 'USD';

    public const VEF = 'VEF';

    public const HTG = 'HTG';

    public const MXN = 'MXN';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BRL,
            self::CAD,
            self::CHF,
            self::CHY,
            self::XDR,
            self::DKK,
            self::EUR,
            self::GBP,
            self::JPY,
            self::NOK,
            self::SCP,
            self::SEK,
            self::USD,
            self::VEF,
            self::HTG,
            self::MXN
        ];
    }
}


