<?php
/**
 * TipoeCFType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * TipoeCFType Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TipoeCFType
{
    /**
     * Possible values of this enum
     */
    public const FACTURA_DE_CREDITO_FISCAL_ELECTRONICA = 'FacturaDeCreditoFiscalElectronica';

    public const FACTURA_DE_CONSUMO_ELECTRONICA = 'FacturaDeConsumoElectronica';

    public const NOTA_DE_DEBITO_ELECTRONICA = 'NotaDeDebitoElectronica';

    public const NOTA_DE_CREDITO_ELECTRONICA = 'NotaDeCreditoElectronica';

    public const COMPRAS_ELECTRONICO = 'ComprasElectronico';

    public const GASTOS_MENORES_ELECTRONICO = 'GastosMenoresElectronico';

    public const REGIMENES_ESPECIALES_ELECTRONICO = 'RegimenesEspecialesElectronico';

    public const GUBERNAMENTAL_ELECTRONICO = 'GubernamentalElectronico';

    public const COMPROBANTE_DE_EXPORTACIONES_ELECTRONICO = 'ComprobanteDeExportacionesElectronico';

    public const COMPROBANTE_PARA_PAGOS_AL_EXTERIOR_ELECTRONICO = 'ComprobanteParaPagosAlExteriorElectronico';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FACTURA_DE_CREDITO_FISCAL_ELECTRONICA,
            self::FACTURA_DE_CONSUMO_ELECTRONICA,
            self::NOTA_DE_DEBITO_ELECTRONICA,
            self::NOTA_DE_CREDITO_ELECTRONICA,
            self::COMPRAS_ELECTRONICO,
            self::GASTOS_MENORES_ELECTRONICO,
            self::REGIMENES_ESPECIALES_ELECTRONICO,
            self::GUBERNAMENTAL_ELECTRONICO,
            self::COMPROBANTE_DE_EXPORTACIONES_ELECTRONICO,
            self::COMPROBANTE_PARA_PAGOS_AL_EXTERIOR_ELECTRONICO
        ];
    }
}


