<?php
/**
 * UnidadMedidaType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Model;
use \Ecfx\EcfDgii\ObjectSerializer;

/**
 * UnidadMedidaType Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UnidadMedidaType
{
    /**
     * Possible values of this enum
     */
    public const BARRIL = 'Barril';

    public const BOLSA = 'Bolsa';

    public const BOTE = 'Bote';

    public const BULTOS = 'Bultos';

    public const BOTELLA = 'Botella';

    public const CAJA_SLASH_CAJON = 'CajaSlashCajon';

    public const CAJETILLA = 'Cajetilla';

    public const CENTIMETRO = 'Centimetro';

    public const CILINDRO = 'Cilindro';

    public const CONJUNTO = 'Conjunto';

    public const CONTENEDOR = 'Contenedor';

    public const DIA = 'Dia';

    public const DOCENA = 'Docena';

    public const FARDO = 'Fardo';

    public const GALONES = 'Galones';

    public const GRADO = 'Grado';

    public const GRAMO = 'Gramo';

    public const GRANEL = 'Granel';

    public const HORA = 'Hora';

    public const HUACAL = 'Huacal';

    public const KILOGRAMO = 'Kilogramo';

    public const KILOVATIO_HORA = 'KilovatioHora';

    public const LIBRA = 'Libra';

    public const LITRO = 'Litro';

    public const LOTE = 'Lote';

    public const METRO = 'Metro';

    public const METRO_CUADRADO = 'MetroCuadrado';

    public const METRO_CUBICO = 'MetroCubico';

    public const MILLONES_DE_UNIDADES_TERMICAS = 'MillonesDeUnidadesTermicas';

    public const MINUTO = 'Minuto';

    public const PAQUETE = 'Paquete';

    public const PAR = 'Par';

    public const PIE = 'Pie';

    public const PIEZA = 'Pieza';

    public const ROLLO = 'Rollo';

    public const SOBRE = 'Sobre';

    public const SEGUNDO = 'Segundo';

    public const TANQUE = 'Tanque';

    public const TONELADA = 'Tonelada';

    public const TUBO = 'Tubo';

    public const YARDA = 'Yarda';

    public const YARDA_CUADRADA = 'YardaCuadrada';

    public const UNIDAD = 'Unidad';

    public const ELEMENTO = 'Elemento';

    public const MILLAR = 'Millar';

    public const SACO = 'Saco';

    public const LATA = 'Lata';

    public const DISPLAY = 'Display';

    public const BIDON = 'Bidon';

    public const RACION = 'Racion';

    public const QUINTAL = 'Quintal';

    public const TONELADAS_DE_REGISTRO_BRUTO = 'ToneladasDeRegistroBruto';

    public const PIE_CUADRADO = 'PieCuadrado';

    public const PASAJERO = 'Pasajero';

    public const PULG_PULGADAS = 'PULGPulgadas';

    public const STAY_PARQUEO_BARCOS_EN_MUELLE = 'STAYParqueoBarcosEnMuelle';

    public const BDJ_BANDEJA = 'BDJBandeja';

    public const HA_HECTAREA = 'HAHectarea';

    public const ML_MILILITRO = 'MLMililitro';

    public const MG_MILIGRAMO = 'MGMiligramo';

    public const OZ_ONZAS = 'OZOnzas';

    public const OZT_ONZAS_TROY = 'OZTOnzasTroy';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BARRIL,
            self::BOLSA,
            self::BOTE,
            self::BULTOS,
            self::BOTELLA,
            self::CAJA_SLASH_CAJON,
            self::CAJETILLA,
            self::CENTIMETRO,
            self::CILINDRO,
            self::CONJUNTO,
            self::CONTENEDOR,
            self::DIA,
            self::DOCENA,
            self::FARDO,
            self::GALONES,
            self::GRADO,
            self::GRAMO,
            self::GRANEL,
            self::HORA,
            self::HUACAL,
            self::KILOGRAMO,
            self::KILOVATIO_HORA,
            self::LIBRA,
            self::LITRO,
            self::LOTE,
            self::METRO,
            self::METRO_CUADRADO,
            self::METRO_CUBICO,
            self::MILLONES_DE_UNIDADES_TERMICAS,
            self::MINUTO,
            self::PAQUETE,
            self::PAR,
            self::PIE,
            self::PIEZA,
            self::ROLLO,
            self::SOBRE,
            self::SEGUNDO,
            self::TANQUE,
            self::TONELADA,
            self::TUBO,
            self::YARDA,
            self::YARDA_CUADRADA,
            self::UNIDAD,
            self::ELEMENTO,
            self::MILLAR,
            self::SACO,
            self::LATA,
            self::DISPLAY,
            self::BIDON,
            self::RACION,
            self::QUINTAL,
            self::TONELADAS_DE_REGISTRO_BRUTO,
            self::PIE_CUADRADO,
            self::PASAJERO,
            self::PULG_PULGADAS,
            self::STAY_PARQUEO_BARCOS_EN_MUELLE,
            self::BDJ_BANDEJA,
            self::HA_HECTAREA,
            self::ML_MILILITRO,
            self::MG_MILIGRAMO,
            self::OZ_ONZAS,
            self::OZT_ONZAS_TROY
        ];
    }
}


