<?php
/**
 * CompanyApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ecfx\EcfDgii\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Ecfx\EcfDgii\ApiException;
use Ecfx\EcfDgii\Configuration;
use Ecfx\EcfDgii\FormDataProcessor;
use Ecfx\EcfDgii\HeaderSelector;
use Ecfx\EcfDgii\ObjectSerializer;

/**
 * CompanyApi Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompanyApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteCompany' => [
            'application/json',
        ],
        'getCompanies' => [
            'application/json',
        ],
        'getCompanyByRnc' => [
            'application/json',
        ],
        'getCurrentCertificate' => [
            'application/json',
        ],
        'updateCertificateCompany' => [
            'multipart/form-data',
        ],
        'upsertCompany' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteCompany
     *
     * @param  string $rnc rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCompany'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteCompany($rnc, string $contentType = self::contentTypes['deleteCompany'][0])
    {
        $this->deleteCompanyWithHttpInfo($rnc, $contentType);
    }

    /**
     * Operation deleteCompanyWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCompany'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteCompanyWithHttpInfo($rnc, string $contentType = self::contentTypes['deleteCompany'][0])
    {
        $request = $this->deleteCompanyRequest($rnc, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteCompanyAsync
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteCompanyAsync($rnc, string $contentType = self::contentTypes['deleteCompany'][0])
    {
        return $this->deleteCompanyAsyncWithHttpInfo($rnc, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteCompanyAsyncWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteCompanyAsyncWithHttpInfo($rnc, string $contentType = self::contentTypes['deleteCompany'][0])
    {
        $returnType = '';
        $request = $this->deleteCompanyRequest($rnc, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteCompany'
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteCompanyRequest($rnc, string $contentType = self::contentTypes['deleteCompany'][0])
    {

        // verify the required parameter 'rnc' is set
        if ($rnc === null || (is_array($rnc) && count($rnc) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rnc when calling deleteCompany'
            );
        }


        $resourcePath = '/company/{rnc}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($rnc !== null) {
            $resourcePath = str_replace(
                '{' . 'rnc' . '}',
                ObjectSerializer::toPathValue($rnc),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCompanies
     *
     * @param  string[]|null $rncs rncs (optional)
     * @param  string[]|null $names names (optional)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesPageParameter|null $page page (optional, default to 1)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesLimitParameter|null $limit limit (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanies'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ecfx\EcfDgii\Model\PaginatedApiResultOfCompanyResponse|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails
     */
    public function getCompanies($rncs = null, $names = null, $page = 1, $limit = 25, string $contentType = self::contentTypes['getCompanies'][0])
    {
        list($response) = $this->getCompaniesWithHttpInfo($rncs, $names, $page, $limit, $contentType);
        return $response;
    }

    /**
     * Operation getCompaniesWithHttpInfo
     *
     * @param  string[]|null $rncs (optional)
     * @param  string[]|null $names (optional)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesPageParameter|null $page (optional, default to 1)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesLimitParameter|null $limit (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanies'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ecfx\EcfDgii\Model\PaginatedApiResultOfCompanyResponse|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCompaniesWithHttpInfo($rncs = null, $names = null, $page = 1, $limit = 25, string $contentType = self::contentTypes['getCompanies'][0])
    {
        $request = $this->getCompaniesRequest($rncs, $names, $page, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\PaginatedApiResultOfCompanyResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ecfx\EcfDgii\Model\PaginatedApiResultOfCompanyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\PaginatedApiResultOfCompanyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCompaniesAsync
     *
     * @param  string[]|null $rncs (optional)
     * @param  string[]|null $names (optional)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesPageParameter|null $page (optional, default to 1)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesLimitParameter|null $limit (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanies'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompaniesAsync($rncs = null, $names = null, $page = 1, $limit = 25, string $contentType = self::contentTypes['getCompanies'][0])
    {
        return $this->getCompaniesAsyncWithHttpInfo($rncs, $names, $page, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCompaniesAsyncWithHttpInfo
     *
     * @param  string[]|null $rncs (optional)
     * @param  string[]|null $names (optional)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesPageParameter|null $page (optional, default to 1)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesLimitParameter|null $limit (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanies'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompaniesAsyncWithHttpInfo($rncs = null, $names = null, $page = 1, $limit = 25, string $contentType = self::contentTypes['getCompanies'][0])
    {
        $returnType = '\Ecfx\EcfDgii\Model\PaginatedApiResultOfCompanyResponse';
        $request = $this->getCompaniesRequest($rncs, $names, $page, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCompanies'
     *
     * @param  string[]|null $rncs (optional)
     * @param  string[]|null $names (optional)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesPageParameter|null $page (optional, default to 1)
     * @param  \Ecfx\EcfDgii\Model\GetCompaniesLimitParameter|null $limit (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanies'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCompaniesRequest($rncs = null, $names = null, $page = 1, $limit = 25, string $contentType = self::contentTypes['getCompanies'][0])
    {



        if ($page !== null && !preg_match("/^-?(?:0|[1-9]\\d*)$/", $page)) {
            throw new \InvalidArgumentException("invalid value for \"page\" when calling CompanyApi.getCompanies, must conform to the pattern /^-?(?:0|[1-9]\\d*)$/.");
        }
        
        if ($limit !== null && !preg_match("/^-?(?:0|[1-9]\\d*)$/", $limit)) {
            throw new \InvalidArgumentException("invalid value for \"limit\" when calling CompanyApi.getCompanies, must conform to the pattern /^-?(?:0|[1-9]\\d*)$/.");
        }
        

        $resourcePath = '/company';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $rncs,
            'Rncs', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $names,
            'Names', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'Page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'Limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCompanyByRnc
     *
     * @param  string $rnc rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanyByRnc'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ecfx\EcfDgii\Model\CompanyResponse|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails
     */
    public function getCompanyByRnc($rnc, string $contentType = self::contentTypes['getCompanyByRnc'][0])
    {
        list($response) = $this->getCompanyByRncWithHttpInfo($rnc, $contentType);
        return $response;
    }

    /**
     * Operation getCompanyByRncWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanyByRnc'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ecfx\EcfDgii\Model\CompanyResponse|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCompanyByRncWithHttpInfo($rnc, string $contentType = self::contentTypes['getCompanyByRnc'][0])
    {
        $request = $this->getCompanyByRncRequest($rnc, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\CompanyResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ecfx\EcfDgii\Model\CompanyResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\CompanyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCompanyByRncAsync
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanyByRnc'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompanyByRncAsync($rnc, string $contentType = self::contentTypes['getCompanyByRnc'][0])
    {
        return $this->getCompanyByRncAsyncWithHttpInfo($rnc, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCompanyByRncAsyncWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanyByRnc'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompanyByRncAsyncWithHttpInfo($rnc, string $contentType = self::contentTypes['getCompanyByRnc'][0])
    {
        $returnType = '\Ecfx\EcfDgii\Model\CompanyResponse';
        $request = $this->getCompanyByRncRequest($rnc, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCompanyByRnc'
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompanyByRnc'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCompanyByRncRequest($rnc, string $contentType = self::contentTypes['getCompanyByRnc'][0])
    {

        // verify the required parameter 'rnc' is set
        if ($rnc === null || (is_array($rnc) && count($rnc) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rnc when calling getCompanyByRnc'
            );
        }


        $resourcePath = '/company/{rnc}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($rnc !== null) {
            $resourcePath = str_replace(
                '{' . 'rnc' . '}',
                ObjectSerializer::toPathValue($rnc),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCurrentCertificate
     *
     * @param  string $rnc rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCurrentCertificate'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ecfx\EcfDgii\Model\CertificateResponse[]|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails
     */
    public function getCurrentCertificate($rnc, string $contentType = self::contentTypes['getCurrentCertificate'][0])
    {
        list($response) = $this->getCurrentCertificateWithHttpInfo($rnc, $contentType);
        return $response;
    }

    /**
     * Operation getCurrentCertificateWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCurrentCertificate'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ecfx\EcfDgii\Model\CertificateResponse[]|\Ecfx\EcfDgii\Model\ProblemDetails|\Ecfx\EcfDgii\Model\ProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCurrentCertificateWithHttpInfo($rnc, string $contentType = self::contentTypes['getCurrentCertificate'][0])
    {
        $request = $this->getCurrentCertificateRequest($rnc, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\CertificateResponse[]',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ecfx\EcfDgii\Model\CertificateResponse[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\CertificateResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCurrentCertificateAsync
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCurrentCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCurrentCertificateAsync($rnc, string $contentType = self::contentTypes['getCurrentCertificate'][0])
    {
        return $this->getCurrentCertificateAsyncWithHttpInfo($rnc, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCurrentCertificateAsyncWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCurrentCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCurrentCertificateAsyncWithHttpInfo($rnc, string $contentType = self::contentTypes['getCurrentCertificate'][0])
    {
        $returnType = '\Ecfx\EcfDgii\Model\CertificateResponse[]';
        $request = $this->getCurrentCertificateRequest($rnc, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCurrentCertificate'
     *
     * @param  string $rnc (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCurrentCertificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCurrentCertificateRequest($rnc, string $contentType = self::contentTypes['getCurrentCertificate'][0])
    {

        // verify the required parameter 'rnc' is set
        if ($rnc === null || (is_array($rnc) && count($rnc) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rnc when calling getCurrentCertificate'
            );
        }


        $resourcePath = '/company/{rnc}/certificate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($rnc !== null) {
            $resourcePath = str_replace(
                '{' . 'rnc' . '}',
                ObjectSerializer::toPathValue($rnc),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateCertificateCompany
     *
     * @param  string $rnc rnc (required)
     * @param  \SplFileObject $certificate certificate (required)
     * @param  string $password password (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateCertificateCompany'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateCertificateCompany($rnc, $certificate, $password, string $contentType = self::contentTypes['updateCertificateCompany'][0])
    {
        $this->updateCertificateCompanyWithHttpInfo($rnc, $certificate, $password, $contentType);
    }

    /**
     * Operation updateCertificateCompanyWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  \SplFileObject $certificate (required)
     * @param  string $password (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateCertificateCompany'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateCertificateCompanyWithHttpInfo($rnc, $certificate, $password, string $contentType = self::contentTypes['updateCertificateCompany'][0])
    {
        $request = $this->updateCertificateCompanyRequest($rnc, $certificate, $password, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateCertificateCompanyAsync
     *
     * @param  string $rnc (required)
     * @param  \SplFileObject $certificate (required)
     * @param  string $password (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateCertificateCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateCertificateCompanyAsync($rnc, $certificate, $password, string $contentType = self::contentTypes['updateCertificateCompany'][0])
    {
        return $this->updateCertificateCompanyAsyncWithHttpInfo($rnc, $certificate, $password, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateCertificateCompanyAsyncWithHttpInfo
     *
     * @param  string $rnc (required)
     * @param  \SplFileObject $certificate (required)
     * @param  string $password (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateCertificateCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateCertificateCompanyAsyncWithHttpInfo($rnc, $certificate, $password, string $contentType = self::contentTypes['updateCertificateCompany'][0])
    {
        $returnType = '';
        $request = $this->updateCertificateCompanyRequest($rnc, $certificate, $password, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateCertificateCompany'
     *
     * @param  string $rnc (required)
     * @param  \SplFileObject $certificate (required)
     * @param  string $password (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateCertificateCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateCertificateCompanyRequest($rnc, $certificate, $password, string $contentType = self::contentTypes['updateCertificateCompany'][0])
    {

        // verify the required parameter 'rnc' is set
        if ($rnc === null || (is_array($rnc) && count($rnc) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rnc when calling updateCertificateCompany'
            );
        }

        // verify the required parameter 'certificate' is set
        if ($certificate === null || (is_array($certificate) && count($certificate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $certificate when calling updateCertificateCompany'
            );
        }

        // verify the required parameter 'password' is set
        if ($password === null || (is_array($password) && count($password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $password when calling updateCertificateCompany'
            );
        }


        $resourcePath = '/company/{rnc}/certificate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($rnc !== null) {
            $resourcePath = str_replace(
                '{' . 'rnc' . '}',
                ObjectSerializer::toPathValue($rnc),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'certificate' => $certificate,
            'password' => $password,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation upsertCompany
     *
     * @param  \Ecfx\EcfDgii\Model\UpsertCompanyRequest $upsert_company_request upsert_company_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertCompany'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function upsertCompany($upsert_company_request, string $contentType = self::contentTypes['upsertCompany'][0])
    {
        $this->upsertCompanyWithHttpInfo($upsert_company_request, $contentType);
    }

    /**
     * Operation upsertCompanyWithHttpInfo
     *
     * @param  \Ecfx\EcfDgii\Model\UpsertCompanyRequest $upsert_company_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertCompany'] to see the possible values for this operation
     *
     * @throws \Ecfx\EcfDgii\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function upsertCompanyWithHttpInfo($upsert_company_request, string $contentType = self::contentTypes['upsertCompany'][0])
    {
        $request = $this->upsertCompanyRequest($upsert_company_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ecfx\EcfDgii\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation upsertCompanyAsync
     *
     * @param  \Ecfx\EcfDgii\Model\UpsertCompanyRequest $upsert_company_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function upsertCompanyAsync($upsert_company_request, string $contentType = self::contentTypes['upsertCompany'][0])
    {
        return $this->upsertCompanyAsyncWithHttpInfo($upsert_company_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation upsertCompanyAsyncWithHttpInfo
     *
     * @param  \Ecfx\EcfDgii\Model\UpsertCompanyRequest $upsert_company_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function upsertCompanyAsyncWithHttpInfo($upsert_company_request, string $contentType = self::contentTypes['upsertCompany'][0])
    {
        $returnType = '';
        $request = $this->upsertCompanyRequest($upsert_company_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'upsertCompany'
     *
     * @param  \Ecfx\EcfDgii\Model\UpsertCompanyRequest $upsert_company_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertCompany'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function upsertCompanyRequest($upsert_company_request, string $contentType = self::contentTypes['upsertCompany'][0])
    {

        // verify the required parameter 'upsert_company_request' is set
        if ($upsert_company_request === null || (is_array($upsert_company_request) && count($upsert_company_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upsert_company_request when calling upsertCompany'
            );
        }


        $resourcePath = '/company';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($upsert_company_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($upsert_company_request));
            } else {
                $httpBody = $upsert_company_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
