<?php
/**
 * AcecfReceptionRequestDtoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AcecfReceptionRequestDtoTest Class Doc Comment
 *
 * @category    Class
 * @description AcecfReceptionRequestDto
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AcecfReceptionRequestDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AcecfReceptionRequestDto"
     */
    public function testAcecfReceptionRequestDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message_id"
     */
    public function testPropertyMessageId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_rnc"
     */
    public function testPropertyCompanyRnc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "progress"
     */
    public function testPropertyProgress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "updated_on"
     */
    public function testPropertyUpdatedOn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "encf"
     */
    public function testPropertyEncf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rnc_emisor"
     */
    public function testPropertyRncEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
