<?php
/**
 * EmisorTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EmisorTest Class Doc Comment
 *
 * @category    Class
 * @description Emisor
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EmisorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Emisor"
     */
    public function testEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rnc_emisor"
     */
    public function testPropertyRncEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "razon_social_emisor"
     */
    public function testPropertyRazonSocialEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nombre_comercial"
     */
    public function testPropertyNombreComercial()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sucursal"
     */
    public function testPropertySucursal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "direccion_emisor"
     */
    public function testPropertyDireccionEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "municipio"
     */
    public function testPropertyMunicipio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "provincia"
     */
    public function testPropertyProvincia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tabla_telefono_emisor"
     */
    public function testPropertyTablaTelefonoEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "correo_emisor"
     */
    public function testPropertyCorreoEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "web_site"
     */
    public function testPropertyWebSite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "actividad_economica"
     */
    public function testPropertyActividadEconomica()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_factura_interna"
     */
    public function testPropertyNumeroFacturaInterna()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_pedido_interno"
     */
    public function testPropertyNumeroPedidoInterno()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informacion_adicional_emisor"
     */
    public function testPropertyInformacionAdicionalEmisor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fecha_emision"
     */
    public function testPropertyFechaEmision()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
