<?php
/**
 * ImpuestoAdicional2Test
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ImpuestoAdicional2Test Class Doc Comment
 *
 * @category    Class
 * @description ImpuestoAdicional2
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ImpuestoAdicional2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ImpuestoAdicional2"
     */
    public function testImpuestoAdicional2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_impuesto"
     */
    public function testPropertyTipoImpuesto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tasa_impuesto_adicional"
     */
    public function testPropertyTasaImpuestoAdicional()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_impuesto_selectivo_consumo_especifico"
     */
    public function testPropertyMontoImpuestoSelectivoConsumoEspecifico()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_impuesto_selectivo_consumo_advalorem"
     */
    public function testPropertyMontoImpuestoSelectivoConsumoAdvalorem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "otros_impuestos_adicionales"
     */
    public function testPropertyOtrosImpuestosAdicionales()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
