<?php
/**
 * InformacionesAdicionalesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InformacionesAdicionalesTest Class Doc Comment
 *
 * @category    Class
 * @description InformacionesAdicionales
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InformacionesAdicionalesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InformacionesAdicionales"
     */
    public function testInformacionesAdicionales()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fecha_embarque"
     */
    public function testPropertyFechaEmbarque()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_embarque"
     */
    public function testPropertyNumeroEmbarque()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_contenedor"
     */
    public function testPropertyNumeroContenedor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_referencia"
     */
    public function testPropertyNumeroReferencia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nombre_puerto_embarque"
     */
    public function testPropertyNombrePuertoEmbarque()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "condiciones_entrega"
     */
    public function testPropertyCondicionesEntrega()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_fob"
     */
    public function testPropertyTotalFob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "seguro"
     */
    public function testPropertySeguro()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flete"
     */
    public function testPropertyFlete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "otros_gastos"
     */
    public function testPropertyOtrosGastos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_cif"
     */
    public function testPropertyTotalCif()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "regimen_aduanero"
     */
    public function testPropertyRegimenAduanero()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nombre_puerto_salida"
     */
    public function testPropertyNombrePuertoSalida()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nombre_puerto_desembarque"
     */
    public function testPropertyNombrePuertoDesembarque()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "peso_bruto"
     */
    public function testPropertyPesoBruto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "peso_neto"
     */
    public function testPropertyPesoNeto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidad_peso_bruto"
     */
    public function testPropertyUnidadPesoBruto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidad_peso_neto"
     */
    public function testPropertyUnidadPesoNeto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cantidad_bulto"
     */
    public function testPropertyCantidadBulto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidad_bulto"
     */
    public function testPropertyUnidadBulto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "volumen_bulto"
     */
    public function testPropertyVolumenBulto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidad_volumen"
     */
    public function testPropertyUnidadVolumen()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
