<?php
/**
 * ItemTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ItemTest Class Doc Comment
 *
 * @category    Class
 * @description Item
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Item"
     */
    public function testItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_linea"
     */
    public function testPropertyNumeroLinea()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tabla_codigos_item"
     */
    public function testPropertyTablaCodigosItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "indicador_facturacion"
     */
    public function testPropertyIndicadorFacturacion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "retencion"
     */
    public function testPropertyRetencion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nombre_item"
     */
    public function testPropertyNombreItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "indicador_bieno_servicio"
     */
    public function testPropertyIndicadorBienoServicio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descripcion_item"
     */
    public function testPropertyDescripcionItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cantidad_item"
     */
    public function testPropertyCantidadItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidad_medida"
     */
    public function testPropertyUnidadMedida()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "precio_unitario_item"
     */
    public function testPropertyPrecioUnitarioItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "otra_moneda_detalle"
     */
    public function testPropertyOtraMonedaDetalle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_item"
     */
    public function testPropertyMontoItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
