<?php
/**
 * OtraMonedaDetalleTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OtraMonedaDetalleTest Class Doc Comment
 *
 * @category    Class
 * @description OtraMonedaDetalle
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OtraMonedaDetalleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OtraMonedaDetalle"
     */
    public function testOtraMonedaDetalle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "precio_otra_moneda"
     */
    public function testPropertyPrecioOtraMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descuento_otra_moneda"
     */
    public function testPropertyDescuentoOtraMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recargo_otra_moneda"
     */
    public function testPropertyRecargoOtraMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "monto_item_otra_moneda"
     */
    public function testPropertyMontoItemOtraMoneda()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
