<?php
/**
 * RespuestaConsultaEstadoCodigoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ecfx\EcfDgii\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RespuestaConsultaEstadoCodigoTest Class Doc Comment
 *
 * @category    Class
 * @description Código asociado al estado de validación del e-CF recibido.             Posibles valores:             * 0No encontrado - No se encontró el comprobante en los registros * 1Aceptado - El e-CF generado por el emisor fue aceptado y tiene validez fiscal * 2Rechazado - Corresponde a la nulidad del comprobante generado por el emisor
 * @package     Ecfx\EcfDgii
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RespuestaConsultaEstadoCodigoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RespuestaConsultaEstadoCodigo"
     */
    public function testRespuestaConsultaEstadoCodigo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
