<?php
/**
 * ApiKeyApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ecfx\EcfDgii\Test\Api;

use \Ecfx\EcfDgii\Configuration;
use \Ecfx\EcfDgii\ApiException;
use \Ecfx\EcfDgii\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ApiKeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiKeyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for newCompanyApiKey
     *
     * .
     *
     */
    public function testNewCompanyApiKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
