<?php
/**
 * EcfApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ecfx\EcfDgii\Test\Api;

use \Ecfx\EcfDgii\Configuration;
use \Ecfx\EcfDgii\ApiException;
use \Ecfx\EcfDgii\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EcfApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EcfApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for anulacionRangos
     *
     * .
     *
     */
    public function testAnulacionRangos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aprobacionComercial
     *
     * .
     *
     */
    public function testAprobacionComercial()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for firmarSemilla
     *
     * .
     *
     */
    public function testFirmarSemilla()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEcfById
     *
     * .
     *
     */
    public function testGetEcfById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAnulaciones
     *
     * .
     *
     */
    public function testListAnulaciones()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for queryEcf
     *
     * .
     *
     */
    public function testQueryEcf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf31
     *
     * .
     *
     */
    public function testRecepcionEcf31()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf32
     *
     * .
     *
     */
    public function testRecepcionEcf32()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf33
     *
     * .
     *
     */
    public function testRecepcionEcf33()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf34
     *
     * .
     *
     */
    public function testRecepcionEcf34()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf41
     *
     * .
     *
     */
    public function testRecepcionEcf41()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf43
     *
     * .
     *
     */
    public function testRecepcionEcf43()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf44
     *
     * .
     *
     */
    public function testRecepcionEcf44()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf45
     *
     * .
     *
     */
    public function testRecepcionEcf45()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf46
     *
     * .
     *
     */
    public function testRecepcionEcf46()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recepcionEcf47
     *
     * .
     *
     */
    public function testRecepcionEcf47()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchAllEcfs
     *
     * .
     *
     */
    public function testSearchAllEcfs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchEcfs
     *
     * .
     *
     */
    public function testSearchEcfs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
