<?php
/**
 * RecepcionApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ECF API
 *
 * ECF API (Electronic Fiscal Receipt).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ecfx\EcfDgii\Test\Api;

use \Ecfx\EcfDgii\Configuration;
use \Ecfx\EcfDgii\ApiException;
use \Ecfx\EcfDgii\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RecepcionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ecfx\EcfDgii
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RecepcionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAcecfReceptionRequest
     *
     * .
     *
     */
    public function testGetAcecfReceptionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEcfReceptionRequest
     *
     * .
     *
     */
    public function testGetEcfReceptionRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchAcecfReceptionRequests
     *
     * .
     *
     */
    public function testSearchAcecfReceptionRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchAcecfReceptionRequestsByRnc
     *
     * .
     *
     */
    public function testSearchAcecfReceptionRequestsByRnc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchEcfReceptionRequests
     *
     * .
     *
     */
    public function testSearchEcfReceptionRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchEcfReceptionRequestsByRnc
     *
     * .
     *
     */
    public function testSearchEcfReceptionRequestsByRnc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
